name: Notificação no Discord

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
      - '**/*.md'
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  changelog-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Enviar atualiações para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          AUTOR="Yampi"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            TITLE="${{ github.event.pull_request.title }}"
            BODY="${{ github.event.pull_request.body }}"

            if [ -z "$BODY" ]; then
              BODY="(sem descrição)"
            fi

            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              STATUS="Atualização fresquinha!"
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{\"content\": \"📝 ${STATUS} por **${AUTOR}**\n**${TITLE}**\n${BODY}\"}" \
                   $DISCORD_WEBHOOK
            fi

          elif [ "${{ github.event_name }}" = "push" ]; then
            COMMITS=$(git log --pretty=format:'- "**Yampi**: \"%s\""' ${{ github.event.before }}..${{ github.sha }} | head -n 10)

            if [ -n "$COMMITS" ]; then
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{\"content\": \"📝 Atualizações na documentação por **${AUTOR}**:\n${COMMITS}\"}" \
                   $DISCORD_WEBHOOK
            fi
          fi
