on:
  push:
    branches:
      - master 
    paths:
      - 'docs/**'
      - '**/*.md'

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar últimas alterações
        uses: actions/checkout@v4

      - name: Enviar notificação para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMITS=$(git log --pretty=format:'- **%an**: _"%s"_' ${{ github.event.before }}..${{ github.sha }})
          if [ -n "$COMMITS" ]; then
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"📘 Atualizações na documentação:\n$COMMITS\"}" \
                 $DISCORD_WEBHOOK
          fi
